### ISSUE TITLE
expose access to specific error types

### ISSUE THREAD

**Issue by jptalton** [sqrrrl/google-api-ruby-client#1]
some error types like NotFound ClientError are not distinguishable from other types of ClientErrors.  

the CleintError exception includes the body as a string, however, due to being passed through api_command's parse_error method, it gets turned into a hash first, and then back into a ruby hash string once it is handed to the exception (eliminating the hack solution of reparsing the body as json)

it would be useful to extract the domain/reason/message into properties of the ClientError.

**Comment by sqrrrl** [comment]
FYI, fixed in google/google-api-ruby-client@2a9fd28176e3d27698520d2d5a8cc0d8b3367732
